### ISSUE TITLE
有完整的部署教程吗

### ISSUE THREAD

**Issue by Arturia169** [yuban10703/setu-nonebot2#10]
可以参考的博客或者git

**Comment by yuban10703** [comment]
这个项目没有..
隔壁的有 https://2333.world/_posts/2022_02_13/%E4%BB%8E0%E5%BC%80%E5%A7%8B%E6%90%AD%E5%BB%BA%E4%B8%80%E4%B8%AA%E8%89%B2%E5%9B%BEBot/

**Comment by Arturia169** [comment]
感谢提供帮助
