### ISSUE TITLE
能否全局反代pixiv域名

### ISSUE THREAD

**Issue by test-black** [yuban10703/setu-nonebot2#13]
梯子非长期稳定的情况下走 cloudflare 去反代是个不错的选择（一天10w次请求余量）
 oauth.secure.pixiv.net 以及获取排名之类的

**Comment by test-black** [comment]
refresh_token 函数替换直连域名也可
![image](https://user-images.githubusercontent.com/28062894/189492421-c86764a4-cef9-4600-83f4-bf3af9fe076a.png)

**Comment by yuban10703** [comment]
不是很懂,,,,

**Comment by test-black** [comment]
https://rainchan.win/2021/08/07/%E5%85%B3%E4%BA%8EPixiv%E5%92%8CSNI%E7%9A%84%E9%82%A3%E4%BA%9B%E4%BA%8B/
