### ISSUE TITLE
想询问请求到的图片都是红叉+请求到了refreshtoken但控制台还是返回刷新失败

### ISSUE THREAD

**Issue by LUDG046** [yuban10703/setu-nonebot2#16]
第一个问题是
![image](https://user-images.githubusercontent.com/51479842/193463453-721b0067-d73b-4f99-b3b4-f274b220905e.png)
群内消息是
![image](https://user-images.githubusercontent.com/51479842/193463515-b911c06d-c65d-40e4-9cf4-4ccafeec6073.png)
测试了很多次都是红叉，有一次连红叉图都没有，发送了一条只有文字的消息。。。
第二个问题 用pixiv_auth.py login后得到了refresh_token 并在.PixivToken.json填进去了（）
[INFO] Get code: Emq0qL_mRIZQoxf7G-cQYwwUTaW0B1_fE8IdZpAq0bg
access_token: HaPtQT-giL3S77z8SfnLQTq-xtGPR***-3xyhJj3oMs
refresh_token: aGJ34wUpf_F4Z1Evd-UTvijiy4bT9***9RwlIq00pFg
expires_in: 3600

在控制台返回的还是
10-02 23:57:12 [INFO] src | 尝试刷新Pixiv_token
10-02 23:57:13 [WARNING] src | 刷新失败
10-02 23:57:13 [INFO] src | 离下次刷新还有:300s
请求大佬帮助

**Comment by yuban10703** [comment]
你没配置代理吧

**Comment by LUDG046** [comment]
感谢回复！
不配置代理的话无法加载插件，控制台返回的是[INFO] src | 已配置socks代理 。所以是代理不好使的意思？

**Comment by yuban10703** [comment]
有可能
