### ISSUE TITLE
想请问下这两个错误应该怎么改进

### ISSUE THREAD

**Issue by namett** [yuban10703/setu-nonebot2#19]
![image](https://user-images.githubusercontent.com/45278496/215455922-c54154f2-69bc-4425-b46a-e2354b7ee7f3.png)

**Comment by namett** [comment]
我google过说是插件未及时更新https://github.com/nonebot/discussions/discussions/218，想问问大家该怎么解决

**Comment by namett** [comment]
nonebot-plugin-setu版本为1.1.9

**Comment by yuban10703** [comment]
可以先换个旧版本nonebot...,我最近可能不会维护...
