### ISSUE TITLE
链接websocket被拒绝

### ISSUE THREAD

**Issue by shimoop** [yuban10703/setu-nonebot2#2]
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 400
11-14 22:15:50 [DEBUG] nonebot | Bot <qq号> from adapter cqhttp connecting to ws://127.0.0.1:8081/
11-14 22:15:50 [ERROR] nonebot | Error while connecting to ws://127.0.0.1:8081/. Try to reconnect...

go-cqhttp正常启动
[2021-11-14 22:15:20] [INFO]: CQ WebSocket 服务器已启动: 127.0.0.1:8081

**Comment by yuban10703** [comment]
https://github.com/nonebot/nonebot2/issues/560

可能是这个问题?

**Comment by shimoop** [comment]
> [nonebot/nonebot2#560](https://github.com/nonebot/nonebot2/issues/560)
> 
> 可能是这个问题?

解决了，又出现一个新问题 cqhttp报错
 failed to accept WebSocket connection: unsupported permessage-deflate parameter: "server_max_window_bits=12"

**Comment by yuban10703** [comment]
不懂...没出现过..

**Comment by shimoop** [comment]
> 不懂...没出现过..

你使用的python版本是什么？

**Comment by yuban10703** [comment]
> > 不懂...没出现过..
> 
> 你使用的python版本是什么？

3.9
