### ISSUE TITLE
求更新！！！

### ISSUE THREAD

**Issue by Fhm-newbie** [yuban10703/setu-nonebot2#21]
大佬，opq寄了da大佬还没做出来新的那如果不麻烦的话您能把这边更新一下吗？反正opq那边说是出新的后插件也都要重新适配的要不俩都搞一搞？

**Comment by Fhm-newbie** [comment]
其实主要就是希望大佬能把base64和transpose这俩选项加上。。。图片不处理太难发出来了。。。

**Comment by Fhm-newbie** [comment]
![图片](https://user-images.githubusercontent.com/63446200/228109078-1ffc585f-8fb9-4b26-8623-c2ee793ea37b.png)
大佬还有一件事就是，您的插件已经不适配最新版本的nonebot了。。。

**Comment by yuban10703** [comment]
等我jb许可证到了就更新

**Comment by Fhm-newbie** [comment]
好的，大佬您加油！

**Comment by Fhm-newbie** [comment]
大佬nb！
就是有一点可惜的是nonebot的发送事件和opq好像不太一样，只要有一个图片风控了整个发送事件就都会结束。。。
所以还请大佬加油！
（话说这个插件是默认base64发送的吗？在opq上开base64后就感觉几乎没有发不出来的情况而这边还是好多风控）
