### ISSUE TITLE
捉个虫，也许不对

### ISSUE THREAD

**Issue by Fhm-newbie** [yuban10703/setu-nonebot2#22]
大佬您好，我怀疑有个bug，src/plugins/nonebot-plugin-setu/__init__.py的66行，经过我的使用体验和与opq的对比我感觉这里应该是info[3]而不是info[2]。。。

**Comment by Fhm-newbie** [comment]
对不起我错了，但是确实是我模仿着opq那边大佬您的修改建议修改一下，把setu.py检查数量的最后一段（183-187行）注释掉后它会变得只发送r18的图片。。。

**Comment by Fhm-newbie** [comment]
![Screenshot_20230331_233750_com tencent mobileqq_edit_1155972064120486](https://user-images.githubusercontent.com/63446200/229166497-04549aa9-99ab-4563-9478-aa87831c02f0.jpg)
就像这样。。。

**Comment by yuban10703** [comment]
没懂

**Comment by Fhm-newbie** [comment]
好的，我整体梳理一遍
我的目标是在开启了r18开关的群里面实现在非指定的情况下只提供非r18的图片，以防止平时出图片时被吞过多，关于这个问题我在opq那边的插件请教过大佬您
于是我对于这边的插件进行了与那边您给的建议一样的修改，既将setu.py的183-187行删掉，但是结果与opq那边的插件不同，它会变成：在开启r18开关的群里面只提供r18图片。 的这个样子
请问大佬，这边这个插件能修改成：在开启r18开关的群里面非指定时会只出色图等级为0的图。 这个样子吗？

**Comment by yuban10703** [comment]
setu.py  246-249行删掉试试

**Comment by Fhm-newbie** [comment]
我两段都删掉了，看样子应该是好了，谢谢大佬帮忙
