### ISSUE TITLE
这项目还维护吗

### ISSUE THREAD

**Issue by test-black** [yuban10703/setu-nonebot2#4]
opq那个框架下总是发不出消息，换了cq-http之后之前的号都没风控问题了

**Comment by test-black** [comment]
![image](https://user-images.githubusercontent.com/28062894/149894578-1cce3ef7-a822-49ff-91d3-bf674fcb7dbb.png)

**Comment by test-black** [comment]
https://github.com/nonebot/discussions/discussions/74

**Comment by yuban10703** [comment]
emmm

**Comment by yuban10703** [comment]
这个仓库目前还不好用

**Comment by yuban10703** [comment]
把nonebot退回b1之前应该能跑起来
