### ISSUE TITLE
setu.py中的adapter还是a16的cqhttp

### ISSUE THREAD

**Issue by siriusty1** [yuban10703/setu-nonebot2#6]
b1运行时会报错

**Comment by yuban10703** [comment]
是b1呀..

**Comment by siriusty1** [comment]
![image](https://user-images.githubusercontent.com/99472108/153561602-79298255-8e28-432d-9d99-b86122a1c41a.png)
![image](https://user-images.githubusercontent.com/99472108/153561954-c20b8673-f5d3-49cd-9507-5b9d479bb6d1.png)

就这个，不知道是我这里没更新还是啥....

**Comment by yuban10703** [comment]
我看下,好像是有问题...

**Comment by yuban10703** [comment]
应该好了
