### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by fatinghenji** [yuban10703/setu-nonebot2#7]
![image](https://user-images.githubusercontent.com/37131177/153649520-506cd8bf-a381-42c9-9a85-3c98e5184f2c.png)
我用的是nonebot.adapters.mirai2，看起来传递消息是没有问题的。但是似乎并不能处理消息内容？
另外，按照`wiki`里面的说法：`路径 : /src/plugins/nonebot-plugin-setu/DB/configs/群号.json，修改实时生效,各个群独立`，我**手动**在相对应的文件夹中建立了对应的json文件，因为插件似乎并没有读取到现存的群号。

**Comment by yuban10703** [comment]
emmm,没试过nonebot.adapters.mirai2,可能是哪里不兼容吧...

**Comment by fatinghenji** [comment]
是否会在将来适配nonebot.adapters.mirai2？

**Comment by yuban10703** [comment]
应该不会适配的,用gocq吧......
